name: run crawler
on: [push, pull_request]

jobs:
   job1:
     name: this is the only job.
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v2
       - uses: actions/setup-python@v3
       - name: run program 
         run: |
           python -m pip install --upgrade pip
           pip3 install -r requirements.txt
           python3 main.py > log.txt 2>&1 

       - name: Commit files
         run: |
           git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
           git config --local user.name "github-actions[bot]"
           git commit -m "Add changes" -a
       - name: Push changes
         uses: ad-m/github-push-action@master
         with:
           github_token: ${{ secrets.GITHUB_TOKEN }}
           branch: ${{ github.ref }}
