name: run crawler
on: [push, pull_request]

jobs:
   job1:
     name: this is the only job.
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v2
       - uses: actions/setup-python@v3
       - name: run program 
         run: |
           python -m pip install --upgrade pip
           pip3 install -r requirements.txt
           python3 main.py > log.txt 2>&1 
       - name: Commit changes
         uses: EndBug/add-and-commit@v8
         with:
           author_name: ${{github.run_id}}
           author_email: 8703199@gmail.com
           message: 'append weather info'
           add: 'forecast.json'
